### ISSUE TITLE
onCancel function not called when dismissing lightbox with swipe gesture

### ISSUE THREAD

**Issue by mattkj** [TrustlyInc/trustly-ios-example#7]
The onCancel function is not called when dismissing lightbox with swipe gesture. It is only called when dismissing with back or close button.

The swipe to dismiss could probably be disabled as it is not really necessary.

**Comment by lukevance** [comment]
Hi @mattkj thanks for the report! We'll address this in an upcoming sprint.

**Comment by lukevance** [comment]
Hi @mattkj, I just wanted to let you know that we addressed this issue in a recent update (#11). Thanks again for reporting it, we appreciate the feedback!
